### ISSUE TITLE
建议添加一处匹配地址

### ISSUE THREAD

**Issue by M1saka10010** [1248289414/scnu_sso_captcha_filler#1]
https://sso.scnu.edu.cn/AccountService/user/index.html
这个链接貌似跟https://sso.scnu.edu.cn/AccountService/user/login.html
是一模一样的，但是有时候也会用到，不知道为什么，建议加入
另外谢谢大佬的项目，真的牛逼

**Comment by 1248289414** [comment]
已添加 :)
